version: "2"

services:
  exchange:
    command: python api.py
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 80
      DB_URL: postgresql://postgres:123@postgres/postgres
    ports:
      - 80:80

  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - exchange-db:/var/lib/postgresql/data

volumes:
  exchange-db: